// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package database

import (
	"database/sql"
	"time"
)

type Device struct {
	ID         interface{}
	DeviceType sql.NullString
	Status     sql.NullString
	CreatedAt  time.Time
	UpdatedAt  time.Time
}
